### ISSUE TITLE
Show user birthdays

### ISSUE THREAD

**Issue by Armadill0** [marttiphpbb/phpbb-ext-calendarmonthview#1]
I know this extension is based on the Calendar Mono extension. One of the main things I am missing is the user birthdays which are already being saved in the database by phpbb itself.

I already have another calendar extension running (https://www.phpbb.de/community/viewtopic.php?t=233145), but I really like the style, customization possibilities and the usability of thr Calendar Extension Set.

It would be awesome if you could implement this. Additionally it would make sense to implement this for the calendarinlineview extension, too. Leave me a message if I should create another issue for that in the corresponding Github project.

**Comment by marttiphpbb** [comment]
Sorry, I've no interest to implement user birthdays. This calendar system is focused on "topic events".
